config/routes.rb
TestMap::Application.routes.draw do
  resources :locations

end

app/models/event.rb
class Event
  attr_reader :latitude, :longitude, :api_key, :max, :date, :city, :within, :events, :title, :venue, :address, :city, :region, :postal_code, :category, :start_date, :end_date, :price

  def initialize(options)

    @latitude = options[:latitude]
    @longitude = options[:longitude]
    @api_key = options[:api_key]
    @max = options[:max]
    @date = options[:date]
    @city = options[:city]
    @within = options[:within]
    @events = []

    urlencoded = URI.encode_www_form({'app_key' => @api_key, 'within' => '94117', 'latitude' => latitude, 'longitude' => longitude, 'max' => '3', 'date' => date})
    
    post_response = Faraday.get do |request|
      request.url "https://www.eventbrite.com/json/event_search?&#{urlencoded}"
    end
   
   
    @events = JSON.parse(post_response.body)['events']
   
    events.each do |event|
      if event.first.first == 'event'
        @title = event['event']['title']
        if event['event']['venue'] == nil
          @venue = ""
          @address = ""
          @city = ""
          @region = ""
          @postal_code = ""
          @latitude = ""
          @longitude = ""
        else
          @venue = event['event']['venue']['name']
          @address = event['event']['venue']['address']
          @city = event['event']['venue']['city']
          @region = event['event']['venue']['region']
          @postal_code = event['event']['venue']['postal_code']
          @latitude = event['event']['venue']['latitude']
          @longitude = event['event']['venue']['longitude']
        end
        @category = event['event']['category']
        @start_date = event['event']['start_date']
        @end_date = event['event']['end_date']
        @price = event['event']['tickets'].first['ticket']['price']
        Location.create(:latitude => @latitude, :longitude => @longitude, :date => @date, :title => @title, :venue => @venue, :address => @address, :city => @city, :region => @region, :postal_code => @postal_code, :category => @category, :start_date => @start_date, :end_date => @end_date, :price => @price)
      end
    end
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name, :gmaps, :latitude, :longitude, :api_key, :max, :date, :city, :within, :events, :title, :venue, :address, :city, :region, :postal_code, :category, :start_date, :end_date, :price
  acts_as_gmappable
 
  def gmaps4rails_address
    address
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @json = @locations.to_gmaps4rails do |location, marker|
      marker.infowindow render_to_string(:partial => "/locations/infowindow", :locals => { :location => location})
      marker.title "#{location.address}"
      marker.json({:address => location.address})
      marker.json({:venue => location.venue})
      marker.picture({:picture => "https://dl.dropbox.com/u/20963921/map_icons/music_rock.png",
                    :width => 32,
                    :height => 32})
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carpooling</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
    <div class="alert alert-info"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-error"><%= flash[:alert] %></div>
  <% end %>
<%= yield %>
<%= yield :scripts %>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :gmaps %><br />
    <%= f.check_box :gmaps %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/_infowindow.html.erb
<h2><%= location.name %></h2>
<h4>address: <%= location.address %></h4>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class="container">
<h1>Listing locations</h1>

<div id="map_canvas">
<%= gmaps4rails(@json) %>
<div>
<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th>Gmaps</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.name %></td>
    <td><%= location.address %></td>
    <td><%= location.longitude %></td>
    <td><%= location.latitude %></td>
    <td><%= location.gmaps %></td>
    <td><%= link_to 'Show', location, :class => 'btn btn-primary' %></td>
    <td><%= link_to 'Edit', edit_location_path(location), :class => 'btn btn-primary' %></td>
    <td><%= link_to 'Destroy', location, method: :delete, :class => 'btn btn-primary', data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>
</div>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Address:</b>
  <%= @location.address %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<p>
  <b>Gmaps:</b>
  <%= @location.gmaps %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>